### ISSUE TITLE
There is a way to share Singletons registrations between two containers?

### ISSUE THREAD

**Issue by lovelycodex** [simpleinjector/Documentation#100]
Hello,
I want to share singletons registration between parent and child container.
There is way to accomplish it?
Basically I want to emulate Unity.CreateChildContainer() behaviour.

**Comment by dotnetjunkie** [comment]
This repository is for the documentation, and is not meant to ask general questions about how to use Simple Injector. Questions about using Simple Injector can be raised [here](https://github.com/simpleinjector/SimpleInjector/issues/new?assignees=&labels=question&template=question-and-feature-request.md&title=). When doing so, please follow the issue template.

**Comment by dotnetjunkie** [comment]
ps. Did you read the documentation and especially [the part about Object Lifetime Management](https://simpleinjector.org/lifestyles)? You might want to first read it before posting your question.
