### ISSUE TITLE
Add a RegisterMvcControllers and RegisterMvcViewComponents overload that take assemblies or types.

### ISSUE THREAD

**Issue by malylemire1** [simpleinjector/Documentation#103]
Hi,

Can you add a RegisterMvcControllers and RegisterMvcViewComponents overload that take assemblies or types.

This will enable adding registration in ConfigureServices. For assemblies it should scan for Microsoft.AspNetCore.Mvc.ControllerBase or ViewComponent in exported types.

Thanks

**Comment by dotnetjunkie** [comment]
The way to do this is by adding:

``` c#
services.AddMvc() 
    .AddApplicationPart(typeof(<class in external assembly>).Assembly);
```

This should be described in the documentation.
