### ISSUE TITLE
Misprint at Object Lifetime Management page

### ISSUE THREAD

**Issue by MichaelSagalovich** [simpleinjector/Documentation#22]
It is saying "...An exception is thrown when a lifetime **soped** registration is requested outside of a scope instance.." (search by word soped for concrete place).

It should be saying "...An exception is thrown when a lifetime **scoped** registration is requested outside of a scope instance..." (soped -> scoped)

**Comment by dotnetjunkie** [comment]
Thanks. Fixed!
