### ISSUE TITLE
Clarification on RegisterConditional

### ISSUE THREAD

**Issue by pdfforge** [simpleinjector/Documentation#38]
While trying to understand the behaviour of the RegisterConditional call, we misinterpreted the documentation a little. There is a note in the docs:

> Note: The predicates are only used during object graph compilation and the predicate’s result is burned in the structure of returned object graph. This disallows changing the graph based on runtime conditions.

We thought that this was obvious, as the resulting object graph would not change. What seems to happen though, is that the class graph is determined here as well and will not be reevaluated, which makes every following call with the same context to produce the same dependecy.

Is that correct?

If so, I would suggest changing the note like this:

> Note: The predicates are only used during object graph compilation and the predicate’s result is burned in the structure of returned object graph. For a given resolution context, an object of the same type will be created on every subsequent call. This disallows changing the graph based on runtime conditions.

Does that make sense and does it reflect the actual behaviour? If so, I would create a pull request with the change.

**Comment by dotnetjunkie** [comment]
> Does that make sense and does it reflect the actual behaviour? 

Your observation is correct and I do agree that the given text is a bit ambiguous. The crucial part in the text is: requesting the same type will always in building up the exact same graph; building the graph based on runtime conditions is disallowed.

Your suggested text is less ambiguous, but since it makes use of the term "resolution context", it introduces some complexity in the text. Perhaps the following is simpler:

> Note: The predicates are only used during object graph compilation and the predicate’s result is burned in the structure of returned object graph. **For a requested type, the exact same graph** will be created on every subsequent call. This disallows changing the graph based on runtime conditions.

Does that make sense?

**Comment by pdfforge** [comment]
Thank you for the quick comment, yes, that makes perfect sense. Shall I create a pull request for that?

**Comment by dotnetjunkie** [comment]
If you create a pull request, I will accept it.

Thanks!

**Comment by dotnetjunkie** [comment]
Fixed in [39](https://github.com/simpleinjector/Documentation/pull/39).
