### ISSUE TITLE
Add documentation about Packaging

### ISSUE THREAD

**Issue by dotnetjunkie** [simpleinjector/Documentation#45]
Nowhere in the documentation SimpleInjector.Packaging is mentioned. This is quite deliberate, since Packaging is usefulness of Packaging is very limited, and its use should be avoided in general. But instead of ignoring it completely, the documentation should describe how and when to use it and when not to use it.

Here's a suggestion for what we should add:

Most applications don’t need packaging. Packinging, installers, modules, registries or whatever your container of choice calls such feature, is only useful in case you have your container configuration in assemblies that are not known at compile time. There is no benefit whatsoever in case your application’s composition root has a compile time reference to the assemblies that hold those registrations.

In case your composition root contains a compile time reference, you are much better of just componentizing your registrations by placing them into static methods and call those methods from your composition root. This gives you the same amount of componentization, while everything is visibly referenced from within the start-up path. In other words, you can F12 to those locations, while still being able to group things together.

Example:

``` c#
public void App_Start()
{
     var container = new Container();
     container.Options.DefaultScopedLifestyle = new WebRequestLifestyle();
     BusinessLayer.Bootstrapper.Bootstrap(container);
     PresentationLayer.Bootstrapper.Bootstrap(container);

     // add missing registrations here.

    container.Verify();
}
```

Packaging features that most containers allow you to do the following (example using Castle):

```
var container = new WindsorContainer();
container.Install(new BusinessLayer.Bootstrapper());
```

This registration however has no benefit over calling a static method.

Containers often also allow you to load those packages using reflection, as does Simple Injector:

``` c#
container.RegisterPackages(
    from file in new DirectoryInfo(pluginDirectory).GetFiles()
    where file.Extension.ToLower() == ".dll"
    select Assembly.LoadFile(file.FullName));
```

But again, this is only useful when you require those assemblies to be loaded dynamically, which is something only few applications need. Downside of using this approach while having assemblies available during compile time, is that those packages are much less discoverable and it can easily fail at runtime, for instance because you forgot to mark the class with the required interface (in that case it will be skipped), or when the package doesn’t have a default constructor.

So again, unless you are loading assemblies (that contain container registrations) at runtime, you don’t need packaging.

**Comment by dotnetjunkie** [comment]
What do you think @TheBigRic, should we add new top-level documentation section (e.g. between 'How to' and 'Advanced Scenarios') or would this be better placed as subsection of the 'How to' section for instance?

**Comment by TheBigRic** [comment]
I would add a section in 'How to'. Given the fact that currently packaging is missing and I quote:

> This is quite deliberate, since Packaging is usefulness of Packaging is very limited, and its use should be avoided in general.

I think a piece of documentation is useful, however giving it a 'main section' will give another impression which is the opposite of the quoted statement.

When it comes to assembly loading I think the documentation should promote the use of what we described [here](https://simpleinjector.readthedocs.io/en/latest/assembly-loading-resolution-conflicts.html) together with `AssemblyName.GetAssemblyName()` in other to prevent people from falling in the duplicate assembly loading pitfall.
