### ISSUE TITLE
Add example of TypesToRegisterOptions

### ISSUE THREAD

**Issue by dotnetjunkie** [simpleinjector/Documentation#49]
The [mixing-collections-of-open-generic-and-non-generic-components](http://simpleinjector.readthedocs.io/en/latest/advanced.html#mixing-collections-of-open-generic-and-non-generic-components) page shows the following example:

``` c#
List<Type> typesToRegister = new List<Type> {
    typeof(DataAnnotationsValidator<>)
};

var assemblies = new[] { typeof(IValidator<>).Assembly) };
typesToRegister.AddRange(container.GetTypesToRegister(typeof(IValidator<>), assemblies));

container.RegisterCollection(typeof(IValidator<>), typesToRegister);
```

The example can be simplified by using the `TypesToRegisterOptions` that has been around for quite some time already:

``` c#
var assemblies = new[] { typeof(IValidator<>).Assembly) };
var typesToRegister= container.GetTypesToRegister(typeof(IValidator<>), assemblies, 
    new TypesToRegisterOptions { IncludeGenericTypeDefinitions = true });

container.RegisterCollection(typeof(IValidator<>), typesToRegister);
```

**Comment by TheBigRic** [comment]
I think the `TypesToRegisterOptions` should exclude composite types and if I'm not mistaken the default is `IncludeComposites = true`.

The new example should therefore be:
``` c#
var assemblies = new[] { typeof(IValidator<>).Assembly) };
var typesToRegister= container.GetTypesToRegister(typeof(IValidator<>), assemblies, 
    new TypesToRegisterOptions 
            { 
                 IncludeGenericTypeDefinitions = true,
                 IncludeComposites = false,
            });

container.RegisterCollection(typeof(IValidator<>), typesToRegister);
```

Or does `RegisterCollection` filter composites no matter what it get's served?

**Comment by dotnetjunkie** [comment]
No, composites are not filtered automatically. I think it would throw a cyclic dependency exception.

**Comment by TheBigRic** [comment]
In that case it will be nice to not include the composites if we want to avoid questions based on our own documentation 🤓

**Comment by dotnetjunkie** [comment]
You are right. In the case of a registration using `RegisterCollection` it is useful to suppress composites, and it is useful to show an example of such thing in the documentation.
