### ISSUE TITLE
Confusing wording in Design Decisions section

### ISSUE THREAD

**Issue by DavidRCulpJr** [simpleinjector/Documentation#52]
In the section [No out-of-the-box support for property injection](https://simpleinjector.readthedocs.io/en/latest/decisions.html#no-out-of-the-box-support-for-property-injection) there is a double-negative that is confusing and likely doesn't says what is expected.

The passage in question states

> ...in none of the cases the container doesn’t know if skipping the property...

From context I believe it should actually be something similar to

> ...in none of the cases does the container know if skipping the property...

**Comment by dotnetjunkie** [comment]
You are correct. Thanks for pointing this out. I will fix this.
