### ISSUE TITLE
Quick start from ASP.NET MVC framework is not friendly to beginner

### ISSUE THREAD

**Issue by wavebit** [simpleinjector/Documentation#54]
Hello,
I am a beginner and I am not familiar with the ASP.NET framework.

I think the quick start document started with a framework is not a good start :(

**Comment by dotnetjunkie** [comment]
Hi Wavebit,

I'm sorry to hear that the documentation doesn't suit your needs. Please bear in mind however that our documentation is not meant to teach you how to work with the ASP.NET framework. There are many blog posts, articles and complete books written about that subject. Our goal is to get you started with Simple Injector in the frameworks you are already familiar with.

There are many great books about ASP.NET MVC, such as [this one](https://www.amazon.com/Pro-ASP-NET-Experts-Voice-ASP-Net/dp/1430265299/ref=sr_1_2?ie=UTF8&qid=1487326360&sr=8-2&keywords=asp.net+mvc) from Adam Freeman, which I can encourage you to read.

Good luck.

**Comment by dotnetjunkie** [comment]
My apologies for my last comment, I misinterpreted your comment.

You make a valid point about showing some framework specific code in the quick start. It might be a good idea to remove any references to specific frameworks, and instead show an example of a [console application](https://simpleinjector.readthedocs.io/en/latest/consoleintegration.html).

**Comment by wavebit** [comment]
yeah, I reviewed two DI frameworks unity and autofac, their documents start from basic program step by step not depending on specific framework.
