### ISSUE TITLE
Is Verify() recommended in production environment?

### ISSUE THREAD

**Issue by YehudahA** [simpleinjector/Documentation#59]
I think that it's important to clarify the cost of verify, it creates all actual types.
For large projects, it is not recommended for production.

**Comment by dotnetjunkie** [comment]
The recommendations are simple: Use `Verify()` until it's not feasible anymore. In case it affects start-up time too much in production, only run it during test and development. If it takes too much time during development, only run it as part of your test suite.

**Comment by YehudahA** [comment]
OK.

**Comment by dotnetjunkie** [comment]
Bit good point. I'll try to incorporate this info in the docs
