### ISSUE TITLE
Add [assembly: CLSCompliant(true)] to SimpeInjector 4

### ISSUE THREAD

**Issue by khodaie** [simpleinjector/Documentation#60]
SimpleInjector 4 has removed the `CLSCompliant `attribute from the assembly! Please consider adding it again.

**Comment by dotnetjunkie** [comment]
Moved to [here](https://github.com/simpleinjector/Documentation/issues/60)

**Comment by dotnetjunkie** [comment]
Mode to [here](https://github.com/simpleinjector/SimpleInjector/issues/405).

**Comment by dotnetjunkie** [comment]
I just pushed [v4.0.2](https://www.nuget.org/packages/SimpleInjector/4.0.2) to NuGet that fixes this problem.
