### ISSUE TITLE
AspNetCore Doc Issue

### ISSUE THREAD

**Issue by steelerc** [simpleinjector/Documentation#61]
When I copy and try to utilize the line:

``` c#
// The following registers a Func<T> delegate that can be injected as singleton,
// and on invocation resolves a MVC IViewBufferScope service for that request.
container.RegisterSingleton<Func<IViewBufferScope>>(
    app.GetRequestService<IViewBufferScope>);
```

from https://simpleinjector.readthedocs.io/en/latest/aspnetintegration.html 
I get an error that the RegisterSingleton is ambiguous.

https://github.com/simpleinjector/SimpleInjector/issues/403 .NET Junkie states that is a known compiler issue and gives an example for the specific case in question.  Please update to what this should be in the docs.  I have currently set mine to:

``` C#
this.container.RegisterSingleton<IViewBufferScope>(app.GetRequestService<IViewBufferScope>());
```

but I am having other issues and I'm not sure that this is correct.

**Comment by dotnetjunkie** [comment]
Registering an `IViewBufferScope` is something different than registering an `Func<IViewBufferScope>`. The former registers a single instance, while the latter registers a factory that allows resolving it when required.

The idea of this `Func<T>` registration is that neither you, nor Simple Injector has any idea of what the lifestyle is that an ASP.NET Core (or a 3rd party) component has in the ASP.NET configuration system. This could be a singleton, but could as well be Scoped or Transient (and as a matter of fact, `IViewBufferScope` is registered as Scoped).

Registering a transient of scoped component as Singleton in Simple Injector can lead to hard to find bugs. This is why instead you should register a factory. This way your code can depend on the factory, and this allows you to resolve it at runtime according to the lifetime it has in the ASP.NET configuration system.

**Comment by dotnetjunkie** [comment]
The correct syntax is the following:

``` c#
container.RegisterSingleton<Func<IViewBufferScope>>(() => app.GetRequestService<IViewBufferScope>())
```

**Comment by dotnetjunkie** [comment]
Fixed
