### ISSUE TITLE
GetCurrentHttpRequestMessage

### ISSUE THREAD

**Issue by nvsoares** [simpleinjector/Documentation#71]
Hello. I'm involved in a web project where we use Simple Injector.

In this project we need to access the request (`HttpRequestMessage`) in several places. One such location is in the logging service. When the api receives a request, a `CorrelationId` is injected into the request header which we can then use throughout the request to log. We are unable to access the request in all locations and we think that the topic "[Getting the current request's HttpRequestMessage](https://simpleinjector.readthedocs.io/en/latest/webapiintegration.html#getting-the-current-request-s-httprequestmessage)" in your documentation would help but we are not achieving the desired result.
Can you help?

I send a small project that exemplifies what we want.
After compiling just run and access the addresses: http://localhost:53983/api/v1/about
Thanks for any help you can give.

[GetCurrentHttpRequestMessage.zip](https://github.com/simpleinjector/Documentation/files/1692255/GetCurrentHttpRequestMessage.zip)

**Comment by dotnetjunkie** [comment]
Please move this question to the [Simple Injector repository](https://github.com/simpleinjector/SimpleInjector/issues/new). Issues in this repository are meant to give feedback and ask improvements of the Simple Injector documentation, not about questions about how to work with Simple Injector.

When you move that question, please include all relevant information, such as exception messages, stack traces, and the add the minimum amount of code that reproduces the issue. Please do _not_ add a zip file with a complete question, but include the code in code blocks inside the issue. Please follow [this guideline](https://stackoverflow.com/help/mcve) to ask a good question.

**Comment by nvsoares** [comment]
Hi, thanks for the reply.
I read the guideline and thought I was respecting the guidelines because I created a small project, with Minimal, Complete, and Verifiable example. What I did wrong was to have sent the zip? The purpose was to facilitate those who could help, because quickly obtain the means to answer my question. 
For future entries can we send small projects with the isolated question?

**Comment by dotnetjunkie** [comment]
There are a few problems with sending a .zip file:
- It is typically way more code than an MCVE.
- It makes it hard to impossible for others to use the question and answer as source. Without an MCVE in the question itself, the question becomes obsolete directly after it has been answered.
