### ISSUE TITLE
SignalR Hub injection

### ISSUE THREAD

**Issue by oferns** [simpleinjector/Documentation#77]
Hi,
any pointers? I would like to inject the IMediator from mediatr into a signalr hub using simple injector but i cannot do it because there is no extension in SI to do it. I am more than willing to contribute but I am not sure what to do! Aspnet core 2.1 
O

**Comment by dotnetjunkie** [comment]
You post this on the Documentation repository, but if I understand correctly, this is a question about how to integrate Simple Injector with SignalR.

Would you therefore mind to move this question to the SimpleInjector repository? This repo is just about the documentation itself.

And can you add any additional details of what you are struggling with? Also keep in mind that have no experience what so ever in SignalR Core, so any details about that or anything that might help me answrring the question is much appreciated.

Also, I'm unsure how the use of Mediatr would change the outcome of your question. So if you think this is relevent specifically to your question, please elaborate on that as well.

Thanks in advance.

**Comment by oferns** [comment]
yes sorry. had a couple of beers!
