### ISSUE TITLE
"Register.Collection" instead of "Collection.Register"

### ISSUE THREAD

**Issue by SoaresMG** [simpleinjector/Documentation#79]
Hey!

I've been reading the collections doc again because after the update it's obsolete.

There are several places in the documentation that says `container.Register.Collection` instead of `container.Collection.Register`.

[Example](https://simpleinjector.readthedocs.io/en/latest/advanced.html?highlight=register.collection) Just search for register.collection and you'll find several places.

Thank you!

**Comment by dotnetjunkie** [comment]
Thanks for pointing this out. I'll fix this a.s.a.p.

**Comment by dotnetjunkie** [comment]
Fixed
