### ISSUE TITLE
WPF: How do I compose UI elements via DI?

### ISSUE THREAD

**Issue by solomon87** [simpleinjector/Documentation#81]
Hello,

I followed your WPF user guide, but it doesn't show how to compose my `MainWindow` with additional UserControls build via SimpleInjector DI. Having guessed, I tried injecting my control into the `MainWindow` constructor and adding it to a `Grid` like so, however I can't get the UserControl to appear. What is the correct way to compose UI elements via DI? (`Main` is a `Grid`)
```xml
<Window x:Class="Iwco.ManualDeploy.Client.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        mc:Ignorable="d"
        Title="Converter"
        MinWidth="300"
        MinHeight="400"
        ResizeMode="NoResize"
        SizeToContent="WidthAndHeight">
    
    <Grid Name="Main">

    </Grid>

</Window>
```
 ``` c#
public partial class MainWindow : Window
 {
     public MainWindow(ConverterControl converterControl)
     {
        InitializeComponent();

        Main.Children.Add(converterControl);
        Main.UpdateLayout();
    }
 }
```

P.S. using `<views: MyUserControl>` no longer works because my `MyUserControl` constructor takes properties via DI.

**Comment by solomon87** [comment]
Okay, I figured this out. I'm a WPF newbie so please excuse my question. Basically I was able to bind any Views set in a MainWindowViewModel property in my xaml like this:

<ContentControl Content="{Binding PropertyToBindTo}" />

**Comment by dotnetjunkie** [comment]
This forum is specifically about the documentation. You can post any new questions about Simple Injector [here](https://simpleinjector.org/forum)
