### ISSUE TITLE
Question: Why I should not store the resolved service in a private field in filter attributes?

### ISSUE THREAD

**Issue by fokkoru** [simpleinjector/Documentation#90]
Hey.

I have found the documentation 

https://simpleinjector.readthedocs.io/en/latest/webapiintegration.html#injecting-dependencies-into-web-api-filter-attributes

And it said that  

> Reverting to the Service Locator pattern means that you need to do the following:
> 
> - Extract all the attribute’s logic -with its dependencies- into a new service class.
> - **Resolve this service from within the filter attribute’s OnActionExecXXX methods, but don’t store the resolved service in a private field.**
> - Call the service’s method.

Could you give more explanation about why I should not do it? Thanks.

**Comment by dotnetjunkie** [comment]
Thank you for this request. I updated the documentation to make it more clear. The documentation now states:

> Web API caches filter attribute instances indefinitely per action, effectively making them singletons. This makes them unsuited for dependency injection, since the attribute's dependencies will be accidentally promoted to singleton as well, which can cause all sorts of concurrency issues. ***This problem is commonly referred to as [Captive Dependencies](https://blog.ploeh.dk/2014/06/02/captive-dependency/) and although Simple Injector tries to [find those issues](https://simpleinjector.readthedocs.io/en/latest/LifestyleMismatches.html), it will be unable to do so in this this case.***
> 
> ...
> 
> Reverting to Service Locator means that you need to do the following:
> 
> * Extract all the attribute's logic -with its dependencies- into a new service class.
> * Resolve this service from within the filter attribute's `OnActionExecXXX` methods, but don't store the resolved service in a private field.
> * Resolve this service from within the filter attribute's `OnActionExecXXX` methods ***(but prevent storing the resolved service in a private field as that could lead to undetectable Captive Dependencies).***
> * Call the service's method.

I hope it makes more sense now.
