### ISSUE TITLE
IOptions commentary

### ISSUE THREAD

**Issue by chadgrant** [simpleinjector/Documentation#92]
I think you're being a bit too extreme by recommending not using IOptions<Config>. The whole point of the abstraction is to allow runtime-reloading of your configs if they change.

If your component takes a dependency on the actual config object you can't change the config at runtime (like kubernetes configs for example) 

It's not that hard to test either, there's a Options.Create<Config>

**Comment by dotnetjunkie** [comment]
That is incorrect. `IOptions<T> does not allow runtime reloading. For that you need to use the `IOptionsSnapshot<T>` abstraction, which the documenation does not mention.

**Comment by chadgrant** [comment]
Yes, it does.

https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.options.ioptionsmonitor-1?view=aspnetcore-2.2

**Comment by dotnetjunkie** [comment]
But the documentation is simply talking about one single interface, not the package as a whole. And still, I would argue that you should prevent your application code from taking a dependency on that package.
